services:
  - type: web
    name: corgi-gif-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GIPHY_API_KEY
        sync: false
